### ISSUE TITLE
Tensorflow CLE quantization bias read error

### ISSUE THREAD

**Issue by h1Logic** [quic/aimet#784] opened 2021-10-22 15:59 UTC
Hi,

when i try to run CLE algorithm in tensorflow i get the following error (modified error message to be more informative):
```
Traceback (most recent call last):
  File "run_adaround.py", line 189, in <module>
    cross_layer_equalization_auto()
  File "run_adaround.py", line 184, in cross_layer_equalization_auto
    cle_session = equalize_model(session, INPUT_OP_NAME, OUTPUT_OP_NAME)
  File "/home/rafal/.local/lib/python3.6/site-packages/aimet_tensorflow/cross_layer_equalization.py", line 761, in equalize_model
    output_op_names)
  File "/home/rafal/.local/lib/python3.6/site-packages/aimet_tensorflow/cross_layer_equalization.py", line 554, in scale_model
    scale_factors = CrossLayerScaling.scale_cls_sets(sess, cls_sets)
  File "/home/rafal/.local/lib/python3.6/site-packages/aimet_tensorflow/cross_layer_equalization.py", line 323, in scale_cls_sets
    scale_factor = CrossLayerScaling.scale_cls_set(sess, cls_set)
  File "/home/rafal/.local/lib/python3.6/site-packages/aimet_tensorflow/cross_layer_equalization.py", line 339, in scale_cls_set
    scale_factor = CrossLayerScaling.scale_cls_set_with_conv_layers(sess, cls_set)
  File "/home/rafal/.local/lib/python3.6/site-packages/aimet_tensorflow/cross_layer_equalization.py", line 358, in scale_cls_set_with_conv_layers
    raise ValueError(f"Only conv layers are supported for cross layer equalization. Got {module}. Cls set {cls_set}")
ValueError: Only conv layers are supported for cross layer equalization. Got name: "bias_value_1"
op: "BiasAdd"
input: "stem/conv2d"
input: "bias_value/read"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "data_format"
  value {
    s: "NHWC"
  }
}
. Cls set (<tf.Operation 'bias_value_1' type=BiasAdd>, <tf.Operation 'bias_value_3' type=BiasAdd>)
```

The model doesn't have biases (except last `Softmax` layer) but CLE seems to add them and then it tries to read them.
```
2021-10-22 17:42:00,535 - tensorflow - INFO - Restoring parameters from ./replace_relu6_with_relu_2021-10-22_17:41:59.325370/temp
...
2021-10-22 17:42:01,004 - ConnectedGraph - WARNING - Unable to identify associated op of module, setting first op in ops_list as associated op.
2021-10-22 17:42:01,017 - ConnectedGraph - WARNING - Unable to identify module name, using name of first op as module name: bias_value_1
...
2021-10-22 17:42:01,041 - ConnectedGraph - WARNING - Unable to identify module name, using name of first op as module name: bias_value_93
2021-10-22 17:42:01,041 - ConnectedGraph - WARNING - Unable to identify associated op of module, setting first op in ops_list as associated op.

```

Same model ran with ADARound algorithm works fine.

Code to run CLE was taken from official documentation - https://quic.github.io/aimet-pages/releases/1.17.0.py37/api_docs/tensorflow_cross_layer_equalization.html#api-tf-cle

My code (in case of need)
```
def cross_layer_equalization_auto():
    """ perform auto cross layer equalization """

    # load a model
    with tf.Session() as session:
        G = load_graph_from_checkpoint()
        session.run(tf.global_variables_initializer())

        cle_session = equalize_model(session, INPUT_OP_NAME, OUTPUT_OP_NAME)

cross_layer_equalization_auto()
```

Python version: 3.6.15
Tensorflow version: 1.15.0
executed on CPU

CLE on SNPE on the same model ran successful

**Comment by quic-ssiddego** [comment] 2021-10-22 21:50
Hi @h1Logic  Thank you for reporting this. Could you please share a checkpoint of the model used in this case. Thank you.

**Comment by h1Logic** [comment] 2021-10-25 16:22
Thanks for reaching out and sorry for a such late replay @quic-ssiddego 
Here you can find repo with all necessary stuff to reproduce the issue https://github.com/h1Logic/quic_aimet_issue784
If you need anything else let me know ;)

**Comment by h1Logic** [comment] 2021-11-02 09:43
hi, @quic-ssiddego is there maybe any update on the issue ? ; )
Thanks in advance

**Comment by quic-ssiddego** [comment] 2021-11-12 03:03
Hi @h1Logic Sorry about the delayed response. Thank you for sharing the checkpoint. Looks like, in this model, there seems to be some structural issue or(could be a bug) that AIMET CLE does not handle. One thing is, if you were to skip the last conv layer in your model, you will be able to perform batch norm folding. Once that's done, you could perhaps use these (low level apis) for CLE https://quic.github.io/aimet-pages/releases/1.17.0.py37/api_docs/tensorflow_primitive_apis_cle.html to ascertain the root cause for this. With low-level APIs you get the flexibility of manually selecting layers and applying individual steps under CLE. This will help zero in on the actual issue. Could you please give this a try and share your observations. Please let me know if you have further questions.

**Comment by quic-hitameht** [comment] 2023-01-30 12:30
Closing this as resolved. If there is another question please re-open or create a new issue. Thank you.

**Closed as completed by quic-hitameht** 2023-01-30 12:30 UTC
