### ISSUE TITLE
Issue in installation with make install command

### ISSUE THREAD

**Issue by pksvision** [quic/aimet#108] opened 2020-07-07 10:51 UTC
Hi.

When running make install command, Im getting this error. I have already setup the googletest folder and docker file.

[  5%] Built target MoDlQuantizationCuda
[ 25%] Built target MoDlQuantization
[ 28%] Built target gtest
[ 31%] Built target gtest_main
[ 44%] Built target MoDlQuantizationTest
[ 47%] Built target MoDlCompressionCuda
[ 53%] Built target MoDlCompression
[ 56%] Built target MoDlCompressionTest
[ 74%] Built target MoDlEqualization
[ 77%] Built target MoDlEqualizationTest
[ 82%] Built target PyModelOptimizations
[ 86%] Built target TrainingExtensionsTfCuda
[ 94%] Built target TrainingExtensionsTf
[ 95%] Built target TorchCppOps
[100%] Built target PyTrainingExtensions
Install the project...
-- Install configuration: ""
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/x86_64-linux-gnu/libpymo.so
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/x86_64-linux-gnu/libaimet_tf_ops.so
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/batch_norm_fold.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/quantizer.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/quantsim.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/layer_database.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/plotting_utils.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/common
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/common/__init__.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/common/tfrecord_generator.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/common/module_identifier.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/common/sub_graph_matcher.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/common/op_defs.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/common/module_identifier_matchers.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/common/operation.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/common/graph_eval.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/common/product.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/common/core.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/common/connectedgraph.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/examples
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/examples/test_models.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/examples/__init__.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/examples/mnist_tf_model.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/cross_layer_equalization.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/compression_factory.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/svd_spiltter.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/compress.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/winnow
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/winnow/__init__.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/winnow/module_reducer_handler.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/winnow/mask_propagation_winnower.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/winnow/winnow.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/winnow/module_reducer.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/channel_pruning
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/channel_pruning/__init__.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/channel_pruning/channel_pruner.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/channel_pruning/data_subsampler.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/channel_pruning/weight_reconstruction.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/utils
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/utils/op
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/utils/op/__init__.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/utils/op/fusedbatchnorm.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/utils/op/relu.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/utils/op/conv.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/utils/__init__.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/utils/constants.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/utils/convert_tf_sess_to_keras.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/utils/common.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/utils/graph_saver.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/quantsim_config
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/quantsim_config/__init__.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/quantsim_config/quantsim_config.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/layer_selector.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/defs.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/svd_pruner.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/svd.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/python/aimet_tensorflow/bias_correction.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/x86_64-linux-gnu
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/x86_64-linux-gnu/aimet_tensor_quantizer-0.0.0-py3.6-linux-x86_64.egg
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/x86_64-linux-gnu/aimet_tensor_quantizer-0.0.0-py3.6-linux-x86_64.egg/AimetTensorQuantizer.cpython-36m-x86_64-linux-gnu.so
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/x86_64-linux-gnu/aimet_tensor_quantizer-0.0.0-py3.6-linux-x86_64.egg/EGG-INFO
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/x86_64-linux-gnu
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/x86_64-linux-gnu/aimet_tensor_quantizer-0.0.0-py3.6-linux-x86_64.egg
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/x86_64-linux-gnu/aimet_tensor_quantizer-0.0.0-py3.6-linux-x86_64.egg/AimetTensorQuantizer.py
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/x86_64-linux-gnu/aimet_tensor_quantizer-0.0.0-py3.6-linux-x86_64.egg/EGG-INFO
-- Up-to-date: /home/prasen/Q_Work/aimet/build/staging/universal/lib/x86_64-linux-gnu/easy-install.pth
CMake Error at TrainingExtensions/torch/cmake_install.cmake:73 (file):
  file INSTALL cannot find
  "/home/prasen/Q_Work/aimet/build/artifacts/site.py".
Call Stack (most recent call first):
  TrainingExtensions/cmake_install.cmake:43 (include)
  cmake_install.cmake:43 (include)

Makefile:73: recipe for target 'install' failed
make: *** [install] Error 1

Please let me know if I have missed anything. 
Thanks,

**Comment by flaviomb** [comment] 2020-07-07 23:45
Hi! I've faced the same problem today. For some reason the site.py is not founded. Can you do the following to see if works?

1) Download the site.py file listed [here](https://drive.google.com/file/d/15gQRxQoTE3X8ExPFNw6-IEZUKf4RGBYx/view?usp=sharing)

2) Put this file in the `/home/prasen/Q_Work/aimet/build/artifacts/` folder

3) Run the install command again

**Comment by quic-bharathr** [comment] 2020-08-04 21:33
Thank you @flaviomb for the work-around. Hopefully that worked for @pksvision. We will look into the root cause shortly.

**Comment by pksvision** [comment] 2020-08-05 14:37
Thank you so much @flaviomb but it is failing at Stage Unit Tests.

**Comment by quic-ssiddego** [comment] 2020-11-06 23:21
@quic-bharathr Hi Bharath - is there any update on this?

**Comment by quic-bharathr** [comment] 2020-11-18 23:56
@pksvision Closing this issue. Please re-open or open a new one if the unit tests are still an issue.

**Closed as completed by quic-bharathr** 2020-11-18 23:56 UTC
Labels: installation
