### ISSUE TITLE
How to quantize a model without data?

### ISSUE THREAD

**Issue by abraham-arun** [quic/aimet#112] opened 2020-07-08 12:24 UTC
Hello,

As per the README, aimet supports Data Free Quantization (DFQ).

But from what I understood from the documentation and the video (https://www.youtube.com/watch?v=QZP2zRb8Vuo&list=PLd0XF75dq-1a7OZTl1kAiM2ZqeKqQpKFH&index=4),
the compute_encodings() call still requires data.

Does aimet support Data Free Quantization as given in the paper? If so, how can I use it?

Thank you.

**Comment by quic-ssiddego** [comment] 2020-08-03 22:41
Hi @abraham-arun  Thank you for the query. Yes, compute_encodings() does require data to find optimal encodings per layer. However, this is in the context of simulating quantization so we can predict quantized accuracy. This simulation just helps you get a quantized accuracy score off-target, does not really help make the model better for quantization. So, it is not a necessary step. You can simply take the model after applying DFQ to target.

**Comment by kanybekasanbekov** [comment] 2020-08-21 03:01
@quic-ssiddego After applying DFG to target, the model is still not quantized, right? By DFQ, do you mean applying Cross-Layer Range Equalization(CLRE) and Bias Correction? As I understood CLRE and Bias Correction are folding Barch Normalization layers and changing weights&biases but not actually quantizing the model. Do you provide a function to quantize the model without using any data? [DFQ paper](https://openaccess.thecvf.com/content_ICCV_2019/papers/Nagel_Data-Free_Quantization_Through_Weight_Equalization_and_Bias_Correction_ICCV_2019_paper.pdf) says as follows- _"Weight quantization ranges are the min and max of the weight tensor. Activation quantization ranges are set without data, by using the learned batch normalization shift and scale parameter vectors β and γ as follows: We compute the activation range for channel i as βi ±n·γi (with n = 6), with the minimum clipped to 0 in case of ReLU activation"_, have you implemented function like this in AIMET?

**Comment by quic-akhobare** [comment] 2020-10-22 04:51
@kanybekasanbekov, AIMET can compute per-layer quantization encodings (scale/offset). Using these AIMET can "simulate" on-target quantized accuracy.

However, AIMET at present does not actually quantize the model. The output from AIMET will still be a FP32 model, but which has been optimized to run on say a 8-bit quantized inference HW. The reason AIMET does not quantize the model is because target runtime tools generally support this already. E.g. the Snapdragon Neural Processing SDK supports this.

Could you briefly explain what you are trying to achieve? Perhaps we might be able to guide your accordingly.

**Comment by nsping13** [comment] 2021-01-07 08:28
Hi, 
Following @kanybekasanbekov question, I would like to reproduce the DFQ paper for different modes of quantization for the weights and activations. For example, what is the accuracy when quantizing to 2 bits and 3 bits?
Thanks :)

**Comment by quic-akhobare** [comment] 2022-11-15 03:24
Unfortunately, DFQ is not a good technique for quantizing to 2 and 3 bits.

Hope that answers your question. Closing this for now. Please re-open if you have a follow-up question.

**Closed as completed by quic-akhobare** 2022-11-15 03:24 UTC
